pct_to_freeze: [0., 0.2, 0.4, 0.6, 0.8, 1.]
batch_size: [2, 4, 8, 16]
model:  [
            'dinov2_vitb14',
            # 'dinov2_vits14',
            # 'dinov2_vitl14',
            # 'deit_tiny_patch16_224',
            # 'deit_small_patch16_224',
            # 'deit_base_patch16_224',
            # 'deit_base_patch16_384',
            # 'efficientnet_b0',
            # 'efficientnet_b1',
            # 'efficientnet_b2',
            # 'efficientnet_b3',
            # 'resnet18',
            # 'resnet34',
            # 'resnet50',
            # 'resnet101',
        ]
amp: [False, True]
opt: ["sgd", "momentum", "adam", "adamw"]
opt_betas: 
    options: ["0.9 0.999", "0 0.99", "0.9 0.99", "0 0.999"]
    only_active_with: {"opt": ["adam", "adamw"]}
momentum: 
    options: [0.0, 0.8, 0.9, 0.95, 0.99]
    only_active_with: {"opt": ["momentum"]}
weight_decay: [0.1, 0.01, 0.001, 0.0001, 0.00001, 0.0]
clip_grad: [None, 1, 10]
layer_decay: [None, 0.65, 0.75]
sched: [None, "cosine", "step", "multistep", "plateau"]
lr: [0.01, 0.005, 0.001, 0.0005, 0.0001, 0.00005, 0.00001]
warmup_lr: [0., 0.000001, 0.00001]
epochs: [50]
warmup_epochs: [0, 5, 10]
decay_rate:
    options: [0.1, 0.5]
    only_active_with: {"sched": ["step", "multistep"]}
decay_epochs: 
    options: [10, 20]
    only_active_with: {"sched": ["step", "multistep"]}
patience_epochs: 
    options: [2,5]
    only_active_with: {"sched": ["plateau"]}
linear_probing: [False, True]
stoch_norm: [False, True]
bss_reg: [0.0, 0.0001, 0.001, 0.01, 0.1] 
sp_reg: [0.0, 0.0001, 0.001, 0.01, 0.1]
delta_reg: [0.0, 0.0001, 0.001, 0.01, 0.1]
cotuning_reg: [0., 0.5, 1., 2., 4.]
cutmix: [0. ,0.1, 0.25, 0.5, 1., 2., 4.] 
mixup: [0., 0.2, 0.4, 1., 2., 4., 8.] 
mixup_prob: [0., 0.25, 0.5, 0.75, 1.]
smoothing: [0., 0.05, 0.1]
drop: [0., 0.1, 0.2, 0.3, 0.4]
data_augmentation: [None, "trivial_augment", "random_augment", "auto_augment"]
auto_augment: 
    options: [None, "v0", "original"]
    only_active_with: {"data_augmentation": ["auto_augment"]}
ra_num_ops: 
    options: [2, 3]
    only_active_with: {"data_augmentation": ["random_augment"]}
ra_magnitude:
    options: [9, 17]
    only_active_with: {"data_augmentation": ["random_augment"]}
